# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('user_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Number')),
            ],
        ),
    ]
